on:
  - push
  - pull_request

jobs:
  lint:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint.yaml@main"

  build:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-build.yaml@main"

  test-unit:
    needs: ["build"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test.yaml@main"
    with:
      foundry-fuzz-runs: 5000
      foundry-profile: "test"
      match-path: "test/**/*.sol"
      name: "Unit tests"

  lint-safe7579:
    needs: ["lint", "test-unit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/safe7579"

  test-safe7579:
    needs: ["build", "test-unit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/safe7579"

  lint-sessionkeymanager:
    needs: ["lint", "test-unit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/sessionkeymanager"

  test-sessionkeymanager:
    needs: ["build", "test-unit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/sessionkeymanager"

  lint-modulekit-examples:
    needs: ["lint", "test-unit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/modulekit-examples"

  test-modulekit-examples:
    needs: ["build", "test-unit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/modulekit-examples"
