on:
  - push
  - pull_request

jobs:
  lint-modulekit:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint.yaml@main"

  build-modulekit:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test.yaml@main"
