on:
  - push
  - pull_request

jobs:
  lint-modulekit:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/modulekit"

  build-modulekit:
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/modulekit"

  lint-safe7579:
    needs: ["lint-modulekit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/safe7579"

  test-safe7579:
    needs: ["build-modulekit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/safe7579"

  lint-sessionkeymanager:
    needs: ["lint-modulekit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/sessionkeymanager"

  test-sessionkeymanager:
    needs: ["build-modulekit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/sessionkeymanager"

  lint-modulekit-examples:
    needs: ["lint-modulekit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-lint-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/modulekit-examples"

  test-modulekit-examples:
    needs: ["build-modulekit"]
    uses: "rhinestonewtf/reusable-workflows/.github/workflows/forge-test-workspaces.yaml@main"
    with:
      match-workspace: "@rhinestone/modulekit-examples"

  test-modulekit-examples-simulate:
    needs: ["build-modulekit"]
    jobs:
      check:
        strategy:
          fail-fast: true

        name: Foundry project
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              submodules: recursive

          - name: Install Foundry
            uses: foundry-rs/foundry-toolchain@v1
            with:
              version: nightly

          - name: Run Forge build
            run: |
              forge --version
              forge build --sizes
            id: build

          - name: Run Forge tests
            run: |
              SIMULATE=true forge test -vvv
            id: test
    with:
      match-workspace: "@rhinestone/modulekit-examples"
